# For more information: https://laravel.com/docs/sail
version: '3'
services:
    mysql:
        image: 'mysql:5.7'
        ports:
            - '3315:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '1234'
            MYSQL_DATABASE: 'test'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: '1234'
        volumes:
            - 'sailmysql:/var/lib/mysql'
volumes:
    sailmysql:
        driver: local
